[S]
OAUTH_TOKEN = "y0_AgAAAABHGDDBAATuwQAAAADusd1bSZvBsJ9eSH2ещьpDw_6yBERArU45a4"
CATALOG_ID = "b1gluhl8h1ulmb8852j6"
ID_KEY = "aje99j71kckucio04tlf"
API = "AQVNyUzOGjKeZLACdq8b96ibAT1WnAUPcRpx5jbX"
RATE = "8000"
CHUNK = "4"
SAMPLE_RATE = 16000
CHUNK_SIZE = 400
INVALID_ELEMENTS = [" ", "", ]
VOICE = "ermil"
EMOTION = "good"
SPEED = "1.0"
MAX_PAUSE_BETWEEN_WORDS_HINT_MS = 500
TYPE = "HIGH"
PORT = "8888"
HOST = "127.0.0.1"