[general]
API = "AQVN0rn-OB5ZvkfqYCmFNXZhRwuGrtGI-W5shkQ5"


RATE = "8000"
CHUNK = "4"
SAMPLE_RATE = 16000
VOICE = "zahar"
EMOTION = "good"
SPEED = "1.0"
MAX_PAUSE_BETWEEN_WORDS_HINT_MS = 500
TYPE = "HIGH"
PORT = "5000"
HOST = "morozyuk-daniil.ru"