# config.toml

[general]
OAUTH_TOKEN = "y0_AgAAAABHGDDBAATuwQAAAADusd1bSZvBsJ9eSH2pDw_6yBERArU45a4"
CATALOG_ID = "b1gluhl8h1ulmb8852j6"
ID_KEY = "aje3am6c2ll41vifto9o"
API = "AQVNw1WMwVakD-T-4Tg0C14ljs3L71K5i3qRX_B2"

token = "y0_AgAAAABHGDDBAATuwQAAAADusd1bSZvBsJ9eSH2pDw_6yBERArU45a4"
cloud-id = "b1gtqcdar7st9r9i6hhd"
folder-id =  "b1gluhl8h1ulmb8852j6"


RATE = "8000"
CHUNK = "4"
SAMPLE_RATE = 16000
CHUNK_SIZE = 400
INVALID_ELEMENTS = [" ", "", ]
VOICE = "zahar"
EMOTION = "good"
SPEED = "1.45"
MAX_PAUSE_BETWEEN_WORDS_HINT_MS = 500
TYPE = "HIGH"
PORT = "5000"
HOST = "127.0.0.1"