[S]
OAUTH_TOKEN = "y0_AgAAAABHGDDBAATuwQAAAADusd1bSZvBsJ9eSH2pDw_6yBERArU45a4"
CATALOG_ID = "b1gluhl8h1ulmb8852j6"
ID_KEY = "aje99j71kckucio04tlf"
API = "AQVNyUzOGjKeZLACdq8b96ibAT1WnAUPcRpx5jbX"
CHANNELS = "1"
RATE = "8000"
CHUNK = "4"
RECORD_SECONDS = 30
WAVE_OUTPUT_FILENAME = "audio.wav"
SAMPLE_RATE = 16000
CHUNK_SIZE = 400
NUM_CHANNELS = 1

[VOICE_SETTING]
INVALID_ELEMENTS = [ " ", "",]
VOICE = "ermil"
EMOTION = "good"
SPEED = "1.1"
MAX_PAUSE_BETWEEN_WORDS_HINT_MS = 500
TYPE = "HIGH"

[SERVER_SETTING]
PORT = "8888"
HOST = "127.0.0.1"

[TELEGRAM_BOT]
BOT_TOKEN = "6603728925:AAEUyY9-cbtVh9grWCB6pXBDLoYVc5auoYk"
MY_ID = 1407136430
